### ISSUE TITLE
Callback upon successful authentication

### ISSUE THREAD

**Issue by sravanco** [natf17/shopify-embedded-app#4]
I want to trigger the loading of product & orders from Shopify to our store(asynchronously) , as soon as the store is successfully authenticated.
I see DefaultInstallFilter is in control of this logic so can override the method to trigger this logic, but this looks like a workaround to me.
So is there a better way to reliably direct control to our project classes, or any other idea you guys already do?

**Comment by sravanco** [comment]
@natf17 any clue, please.

**Comment by sravanco** [comment]
I have finally made this a module project and modified it as I need.

**Comment by vishu184** [comment]
@sravanco Hi Can you share some code snippet of your implementation and for fetching products and order how you call that api how you done authentication for shopify admin api
